version: '3'
services:
  odoo:
    image: odoo:18.0
    platform: linux/amd64
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  postgres:
    image: postgres:15
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
